### ISSUE TITLE
failure is not an option

### ISSUE THREAD

**Issue by csloz** [MiSTer-devel/Updater_script_MiSTer#10]
Add a return value of non zero to the script, and notification on completion of script if a curl download fails.

eg, it fails somewhere, set a variable indicating that, when script completes -

Add in "Failed attempting an update"  before the  "Done!"
And return a non zero.

If you want to get fancy can maybe return 1,2,3... for how many failed.

**Comment by Locutus73** [comment]
Implemented in version 4.0
https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/6d6026ee24d557dff041cd9378c5c462bc2e2dc4
