### ISSUE TITLE
add new variable to addition repos

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Updater_script_MiSTer#14]
Hi

if we add ADDITIONAL_REPOSITORIES section in an ini file, the original urls for ADDITIONAL_REPOSITORIES in mister_updater.sh are not processed because they are replaced.

can you add an ADDITIONAL_REPOSITORIES_ADD or something where we can add more repositories and have the original ADDITIONAL_REPOSITORIES in the queue to be processed also?

Thanks

**Comment by wesclemens** [comment]
This can already be done using '+=' instead of '='.  I have submitted a pull request to add an example of this.

**Comment by eubrunosilva** [comment]
thanks but i didn't realized that additional repos doesn't solve my problem... i need to the timestamp be processed (like the oficial cores)

**Comment by wesclemens** [comment]
Can you give an example repo that your trying to auto update with?

**Comment by eubrunosilva** [comment]
just take a look at the code... also locutus told me that... this will replace files with the same name...
