### ISSUE TITLE
download text output misaligned

### ISSUE THREAD

**Issue by onaryc** [MiSTer-devel/Updater_script_MiSTer#16]
Hi,

I've notice that at some point, when updating my mister, the download text output is misaligned. 

I think that a carriage return is perhaps missing somewhere but it is strange because it happens only after some time.

It is not very important though, the system is perfectly updated afterwards.

**Comment by onaryc** [comment]
I've updated my mister and look closely at the output : in fact the download text (from curl i think) is desynchronized, it appears before the corresponding "check xxx" text.

**Comment by Locutus73** [comment]
Do you see this with PARALLEL_UPDATE enabled?

**Comment by onaryc** [comment]
Sorry for the late response, i will check that asap
