### ISSUE TITLE
Possible Main/Menu update problem.

### ISSUE THREAD

**Issue by sorgelig** [MiSTer-devel/Updater_script_MiSTer#18]
Not sure if this is applicable to updater or not. Close the issue if it's solved.

It's possible that user do updates by script, but at some point he may use SD installer to update the SD card with latest Linux which may downgrade MiSTer/Menu to the versions were actual at Linux release time. And if updater relay only on copies it downloaded before it may not notice the MiSTer and Menu aren't match to latest and won't update till new releases.

**Comment by Locutus73** [comment]
You are right, I'll think about that.
Thank you.

**Comment by sorgelig** [comment]
May be add md5/crc compare between timecoded and non-timecoded versions additionally?

**Comment by Locutus73** [comment]
Implemented with https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/ded04c4417109c71324ff9fa94d50bb6e67ba2e6

Thank you.
