### ISSUE TITLE
Feature request: list of updated cores at the end

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Updater_script_MiSTer#24]
Hi

its possible to display at the end a list of updated cores?
if you aren't looking you don't know what cores were updated...

Thanks

**Comment by Locutus73** [comment]
Implemented in version 4.0
https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/6d6026ee24d557dff041cd9378c5c462bc2e2dc4
