### ISSUE TITLE
A way to detect of update with the same datecode.

### ISSUE THREAD

**Issue by sorgelig** [MiSTer-devel/Updater_script_MiSTer#25]
Sometimes a hotfix is required to be released which may have the same date code in the file name. So i wonder if it possible to detect it from updater script, so it won't be missed. 
Can you check the file size without downloading so you can compare it with existing file? For rbf file every build usually have different file size, so it's enough to check just this parameter to find if files with same datecode are different.

**Comment by Locutus73** [comment]
Yeah, I can check something like filesize or local file date vs github timestamp... by the way, the updater accepts timestamps with an additional letter in the end (I remember it happened once in a core): so i.e. SNES_20200103.rbf could be followed by SNES_20200103a.rbf and SNES_20200103b.rbf, keeping track of multiple daily releases. Please let me know what you prefer.

**Comment by sorgelig** [comment]
file timestamp i think is not robust because it may include time zone which will make it hard to distinguish. File size should be a good feature to check if you don't need to download it before check the size. Index at the end also good to have. Probably i need to check if my code cope with additional index and add proper handling.

**Comment by Locutus73** [comment]
I already use file timestamp for additional repos (scripts, palettes, etc.) and all time-dates (both local files and GitHub ones) are checked as GMT, so no timezone problem; I don't have the file size in the "releases" page I download for checking available files, so any method to check filesize would require an additional HTTP GET slowing down the update process (I just made it quickier skipping a page download, and then again slower with MRA update/download :D ). Let me know if the additional letter is a viable solution.
Thank you.

**Comment by sorgelig** [comment]
Btw, unrelated thinking:
github showing latest updated cores first. So updater can take advantage of it. At least for cores from MiSTer-devel (another advantage of having cores in a single group). So if after some repository updater doesn't find the update, then it can stop.

**Comment by sorgelig** [comment]
I've fixed the handling of additional letter (didn't pushed yet, need to test more), so it's viable solution. Actually my code now handles any amount of letters after datecode but single letter is basically enough for hot fixes.

**Comment by Locutus73** [comment]
> Btw, unrelated thinking:
> github showing latest updated repositories first. So updater can take advantage of it. At least for cores from MiSTer-devel (another advantage of having cores in a single group). So if after some repository updater doesn't find the update, then it can stop. It may greatly reduce updating time.

You know what? That's a brilliant idea! Maybe with a slightly different process (I think I can get all the repo last update dates in a call and compare them to the latest successful update), but it can dramatically reduce update time. Thanks for the hint. I'll work to this after the MRA and a update/summary log (which will be used for the latest successful update date retrieval)



> I've fixed the handling of additional letter (didn't pushed yet, need to test more), so it's viable solution. Actually my code now handles any amount of letters after datecode but single letter is basically enough for hot fixes.

Ok, so do we proceed this way instead of the local vs github timedate check?

Thank you in advance.

**Comment by sorgelig** [comment]
yeah, letter should be good way as it will be more visible for user

**Comment by wesclemens** [comment]
GitHub provides consitant ETag headers on raw objects so if we stored the ETag of the current version we would be able to detect changes easily by adding the ```If-None-Match``` header to the curl request.

Also, is there a reason why MiSTer doesn't use the GitHub release system it is quite robust. If MiSTer ever wanted to do a CI/CD pipeline like Travis CI it would need to be moved over to a more formal release systems. I personally would be inrested in seeing if we could get Quartus builds to work in the free teir of Travis.

**Comment by Locutus73** [comment]
Regardless of which is the best/most elegant/most canonical way of releasing cores and stuff (I won’t discuss this here) I want to point out some things about the updater: its main, original, primary goal was and is to automagically work without any alteration of Sorgelig’s workflow and without any additional effort by anyone. It must be self-sufficient (no additional external resources) and completely transparent to MiSTer developers. If/when Sorgelig will change his workflow for his own convenience, the updater will cope with that.

**Comment by sorgelig** [comment]
Current release schema is pretty much convenient for developers. Everything is done inside the git console without going to website and do additional work to make a release. This is very inconvenient.
All releases are just single file, so there is no point to add more work for developers.

I've tired to explain this again and again!
