### ISSUE TITLE
Possibility to add a list of cores not to update

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Updater_script_MiSTer#26]
Hi

for now we can only make a filter for cores/categories we want to update.
It's possible to have a filter for cores/categories we don't want to update?

Thanks

**Comment by Locutus73** [comment]
Implemented in version 4.0
https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/6d6026ee24d557dff041cd9378c5c462bc2e2dc4
