### ISSUE TITLE
Debian package repository

### ISSUE THREAD

**Issue by kylophone** [MiSTer-devel/Updater_script_MiSTer#27]
Since MiSTer runs Linux, it should be possible to maintain a Debian package repository and install cores, fonts, etc, using a package manager (`apt` or similar). Packages could be versioned, signed, have certain dependencies, etc. Is there any reason to prefer an updater script over that methodology?

**Comment by sorgelig** [comment]
Not suitable for MiSTer developing process.
MiSTer has no package manager. It's not based on any standard Linux distribution.

**Comment by kylophone** [comment]
> Not suitable for MiSTer developing process.
> MiSTer has no package manager. It's not based on any standard Linux distribution.

There's no reason one couldn't be ported. `apt`, `yum`, and `dpkg` they should all work fine, I think. Any package manager should then be configured to pull packages from a MiSTer package repository.

**Comment by sorgelig** [comment]
There is no reason to port, i would say. The way it works is already perfect.

**Comment by kylophone** [comment]
> There is no reason to port, i would say. The way it works is already perfect.

What about #25 and #26? A real package manager would solve these problems (and more).

**Comment by kylophone** [comment]
Also worth considering: The current method downloads a shell script from the web, and then executes it as `root`.

**Comment by sorgelig** [comment]
There are no real problems requiring package managers and system administrator with Linux experience to serve the MiSTer needs.

> Also worth considering: The current method downloads a shell script from the web, and then executes it as `root`. A lot of trust involved there.

Don't use updater script. Update by hands - most releases are a single files which you can copy yourself. Also, don't keep sensitive information on MiSTer and you will have nothing to loose.

P.S.: Those who want make a Linux computer from MiSTer should pass by.
