### ISSUE TITLE
MRA Files with an Apostrophe is not downloading correctly

### ISSUE THREAD

**Issue by RetroDriven** [MiSTer-devel/Updater_script_MiSTer#30]
It appears that these MRA files are not downloading as RAW files.

**Comment by Locutus73** [comment]
Solved with version 3.6.1
https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/6d1ebf1873a8ce5dd0e1a095c30467e45206b2f7

**Comment by Locutus73** [comment]
Solved with version 3.6.1
https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/6d1ebf1873a8ce5dd0e1a095c30467e45206b2f7
