### ISSUE TITLE
Mame and hbmame folder creation

### ISSUE THREAD

**Issue by RetroDriven** [MiSTer-devel/Updater_script_MiSTer#31]
Would it be possible to specify if you're using the Games folder for Mame and hbmame? Right now the script creates both folders in your Arcade path/folder regardless. It's not a huge deal but it's unnecessary to have those folders there if you're using the Games folder instead of the Arcade folder.

**Comment by Locutus73** [comment]
Implemented in 4.0.6
https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/53d4ed50a582ba7833d68de267faa58b63c51e77
and refined in 4.0.7
https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/5c7968cca525adc53b8690c8f762ab49cd2e852e
