### ISSUE TITLE
base_path ini not working

### ISSUE THREAD

**Issue by filipjk** [MiSTer-devel/Updater_script_MiSTer#39]
updater_ 4.0.4 version
content of update.ini / mister_updater.ini
BASE_PATH="/media/usb0"
PARALLEL_UPDATE="false"

Through the menu F12 'Switch to USB' is done: Storage: USB
/etc/usbmount/usbmount.config = updated to remove the noexec on mountoptions

which location should be used
/media/fat/update.ini
/media/fat/mister_updater.ini
/media/fat/Scripts/update.ini
/media/fat/Scripts/mister_updater.ini
/media/fat/Scripts/.mister_updater/update.ini
/media/fat/Scripts/.mister_updater/mister_updater.ini
/media/usb0/update.ini
/media/usb0/mister_updater.ini
/media/usb0/Scripts/update.ini
/media/usb0/Scripts/mister_updater.ini
/media/usb0/Scripts/.mister_updater/update.ini
/media/usb0/Scripts/.mister_updater/mister_updater.ini

I would expect that /media/usb is used to store the downloaded files,, expect for the /linux, MiSTer, Menu_MiSTer;

You can see during the download that the parameter is seen.
But data is still stored on /media/fat/ instead of the configured /media/usb0

output on screen
it downloads the file to /media/fat/xxxxx
delete old file
create directory /media/usb0/xxxxx

so alot of content is still created on /media/fat and not the choosen /media/usb0

**Comment by Locutus73** [comment]
This should be fixed with version 4.0.6
https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/53d4ed50a582ba7833d68de267faa58b63c51e77
Can you test again and report back?

Thank you in advance.

**Comment by filipjk** [comment]
Of course i'll test :)
In the weekend. Week Evening is study time for fpga for the time being.

Op ma 4 mei 2020 11:32 schreef Locutus73 <notifications@github.com>:

**Comment by filipjk** [comment]
Ah found my email back.
Yes the base path now works for me.

Best regards,

Filip

Op ma 4 mei 2020 om 12:31 schreef Filip Kindt <filip.kindt@future4us.eu>:
