### ISSUE TITLE
Updater fails on SEGASYS1_MiSTer

### ISSUE THREAD

**Issue by Kreeblah** [MiSTer-devel/Updater_script_MiSTer#51]
It looks like the branch for this project is named "main" rather than "master", which is causing the updater script to receive a 404 when attempting to update this core.

**Comment by sorgelig** [comment]
This is github new policy. All new repositories will have "Main" branch instead of "Master."

**Comment by theypsilon** [comment]
This should fix it: https://github.com/MiSTer-devel/Updater_script_MiSTer/pull/52

**Comment by Kreeblah** [comment]
If future repositories are going to have main branches, would it make more sense to special case all of the existing ones and default to main?

**Comment by sorgelig** [comment]
I believe there is a way to detect a default branch. Script shouldn't hardcode the branch name. When you open repository, github automatically opens default branch.

**Comment by Kreeblah** [comment]
Turns out there was a way to do that, yes.  I submitted https://github.com/MiSTer-devel/Updater_script_MiSTer/pull/53 which parses out the default branch from the branch listing page and uses that for requests.  It seems to work fine in my testing.

**Comment by Locutus73** [comment]
Fixed by https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/c23350031d40300186c77ac51219e6bee9823cec and https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/ef7593624c672309c78d5acc57018d689de37f82
