### ISSUE TITLE
404 trying to update Asteroids and AsteroidsDeluxe

### ISSUE THREAD

**Issue by ddstevens** [MiSTer-devel/Updater_script_MiSTer#54]
The repository names pulled from https://api.github.com/orgs/mister-devel/repos don't match the actual repository names (case issue) causing the update script to fail.

Arcade-Asteroids_MiSTer != Arcade-Asteroids_MISTer
Arcade-AsteroidsDeluxe_Mister != Arcade-AsteroidsDeluxe_MISTer

**Comment by birdybro** [comment]
Looking at the API now, I don't see anything with the string `Arcade-A*` at all (not even Arcade-Astrocade_MiSTer, which works) and there are only a tiny handful of `Arcade-*` cores included in the API. So if this were the reason why the script is failing to update this arcade core, then it would fail to update all but a tiny handful of Arcade cores.

**Comment by dshadoff** [comment]
In case it's hard to see from the example above, the updater script is searching for repositories suffixed by "_MISTer" with a capital "I" in the case of these two Asteroids variants, where it doesn't search with a capital "I" for others.

Complicating matters, the actual Asteroids Deluxe repository doesn't capitalize the "ST", which I believe should be considered a separate bug (for the maintainer of that repo).

**Comment by dshadoff** [comment]
OK, I figured this out and corrected it.

The wiki page reference needs to point to the correct repository - and it must have the correct case.  Apparently the wiki system doesn't care about case, and will find the repository link even with incorrect case, but the updater script requires correct case.
