### ISSUE TITLE
MRA files not downloading on fresh sd card

### ISSUE THREAD

**Issue by molnara** [MiSTer-devel/Updater_script_MiSTer#65]
I created a fresh sd card using mr. fusion image and ran update_all and everything downloads except the MRA files. The alternative mra files download fine though. I checked the logs and it shows the following for every arcade game:

Checking Arcade-[ArcadeNameHere]_MISTer
Nothing to update
Checking MRA files

**Comment by werpu** [comment]
Same problem here, I opened a thread on the forum https://misterfpga.org/viewtopic.php?f=27&t=2176&sid=2f8fe8825edd73fa7e4514b3ad8bee28

2 people responded already, so it is not a configuration issue, something in the scripts is broken

**Comment by Kikusui1** [comment]
In addition to the mra files, the scripts folder isn't being populated with the additional scripts.

**Comment by Locutus73** [comment]
Fixed with v4.0.12 https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/689b0f100f696eca67c70d524516e45eeee79dd0
