### ISSUE TITLE
MRA files not downloading

### ISSUE THREAD

**Issue by JimmyStones** [MiSTer-devel/Updater_script_MiSTer#66]
Just ran the updater script to pick up two updated cores I pushed yesterday and the RBFs were updated but the MRA was not.  (examples were Time Pilot and Pengo).

Cheers,
Jim

**Comment by JimmyStones** [comment]
As a follow up, today I updated Donkey Kong and only 3/4 of the MRAs came down in the update.   The only one that didn't was 'Radar Scope.mra'

Cheers,
Jim

**Comment by Locutus73** [comment]
Fixed with https://github.com/MiSTer-devel/Updater_script_MiSTer/commit/429c003f0b8991796d5a079cc7115adec7c1fe3f
