### ISSUE TITLE
Updater script still expects .rar kernel, but it's now .7z

### ISSUE THREAD

**Issue by gschmidl** [MiSTer-devel/Updater_script_MiSTer#75]
Updating to the latest Linux kernel fails as of 2021-08-29 as it is now .7z, not .rar, and the updater can't handle it:

![image](https://user-images.githubusercontent.com/20334/131257122-3b20c07a-9511-4ff1-b15f-75709234bd33.png)

**Comment by bootsector** [comment]
In my case the release distribution is being downloaded as a html file.

**Comment by gschmidl** [comment]
Looks like it's fixed.
