### ISSUE TITLE
downloaded file verification [change request]

### ISSUE THREAD

**Issue by csloz** [MiSTer-devel/Updater_script_MiSTer#9]
Suggest add a md5 / sha hash or file size verification of downloaded files to the updater script.

i.e. download file - compare.  if good, install, if not, retry or skip till next run

-

Its an issue as I was getting black screen on some cores.  Manually compared - file sizes didn't look the same as the github size,  deleted from the _core's folders, the redownloaded again via the script, which worked.  

Right now it just assumes things worked out, which isn't always the case!

**Comment by Locutus73** [comment]
Implemented with Version 3.1 - 2019-06-16 - Checking cURL download success and restoring old files when needed.
